In [1]:
import pandas as pd

In [2]:
path = '/data/niezl/TCT/TCT_Data/Detection/0513/影像标注结果.csv'
csv = pd.read_csv(path)

In [3]:
csv.head()

,用户编号,影像结果编号,序列编号,阴阳性,病灶,影像工具,影像结果类型,影像结果,自定义内容,恶性细胞分类
0,5274,173686,fc71b18c13a44fb3b9b7226dfad8416f,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":7.065693430656934,""y"":136.95377...",NaN,1
1,5274,173687,fc71b18c13a44fb3b9b7226dfad8416f,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1764.068126520681,""y"":443.13381...",NaN,1
2,5274,173685,fc71b18c13a44fb3b9b7226dfad8416f,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":741.8978102189781,""y"":991.90267...",NaN,1
3,5274,173690,fc71b18c13a44fb3b9b7226dfad8416f,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":296.7591240875912,""y"":937.73236...",NaN,1
4,5274,173691,fc71b18c13a44fb3b9b7226dfad8416f,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1135.221411192214,""y"":12.126520...",NaN,1

In [4]:
csv.loc[csv['序列编号']=='594b835c56a54b749e5f66e7e6d7f97d']

,用户编号,影像结果编号,序列编号,阴阳性,病灶,影像工具,影像结果类型,影像结果,自定义内容,恶性细胞分类
268,5274,146262,594b835c56a54b749e5f66e7e6d7f97d,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":405.1628865979381,""y"":519.18350...",NaN,1
269,5274,146266,594b835c56a54b749e5f66e7e6d7f97d,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1486.9278350515465,""y"":537.1463...",NaN,1
270,5274,146264,594b835c56a54b749e5f66e7e6d7f97d,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1568.758762886598,""y"":349.53402...",NaN,1
271,5274,146265,594b835c56a54b749e5f66e7e6d7f97d,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1337.237113402062,""y"":642.92783...",NaN,1
272,5274,146268,594b835c56a54b749e5f66e7e6d7f97d,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1648.5938144329898,""y"":808.5855...",NaN,1
273,5274,146278,594b835c56a54b749e5f66e7e6d7f97d,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1267.3814432989693,""y"":275.6865...",NaN,1
274,5274,146276,594b835c56a54b749e5f66e7e6d7f97d,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1474.9525773195878,""y"":413.4020...",NaN,1
275,5274,146288,594b835c56a54b749e5f66e7e6d7f97d,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":355.26597938144323,""y"":662.8865...",NaN,1
276,5274,146302,594b835c56a54b749e5f66e7e6d7f97d,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":862.2185567010309,""y"":710.78762...",NaN,1
277,5274,146303,594b835c56a54b749e5f66e7e6d7f97d,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":77.83917525773185,""y"":42.169072...",NaN,1

In [5]:
csv.loc[csv['序列编号']=='c9006d2c3ab54de4bd53069ebd084604']

,用户编号,影像结果编号,序列编号,阴阳性,病灶,影像工具,影像结果类型,影像结果,自定义内容,恶性细胞分类
4158,5213,155799,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1546.4216216216214,""y"":337.4126...",NaN,1
4159,5213,155801,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":801.4846846846846,""y"":76.684684...",NaN,1
4160,5213,155807,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1377.7153153153151,""y"":589.3765...",NaN,3
4161,5213,155804,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":626.2054054054054,""y"":433.81621...",NaN,1
4162,5213,155810,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":829.9675675675675,""y"":184.04324...",NaN,3
4163,5213,155817,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":762.0468468468467,""y"":626.62342...",NaN,1
4164,5213,155823,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":102.55855855855853,""y"":492.9729...",NaN,3
4165,5213,155821,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1239.6828828828827,""y"":1025.383...",NaN,3
4166,5213,155844,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1191.481081081081,""y"":904.87927...",NaN,3
4167,5213,155851,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1268.1657657657656,""y"":589.3765...",NaN,3
4168,5213,155865,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1721.7009009009007,""y"":17.52792...",NaN,1
4169,5213,155872,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1480.6918918918918,""y"":19.71891...",NaN,3
4170,5213,155878,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":713.8450450450449,""y"":911.45225...",NaN,3
4171,5213,155886,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":177.0522522522522,""y"":617.85945...",NaN,1
4172,5213,155890,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1252.8288288288286,""y"":13.14594...",NaN,1
4173,5213,155909,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1406.198198198198,""y"":957.46306...",NaN,3
4174,5213,155913,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":218.68108108108106,""y"":6.572972...",NaN,1
4175,5213,155917,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":128.8504504504504,""y"":26.291891...",NaN,3
4176,5213,155922,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1555.1855855855854,""y"":479.8270...",NaN,3
4177,5213,155920,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":832.1585585585584,""y"":205.95315...",NaN,1
4178,5213,155926,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1699.7909909909908,""y"":1010.046...",NaN,1
4179,5213,155928,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":380.81441441441433,""y"":407.5243...",NaN,1
4180,5213,155938,c9006d2c3ab54de4bd53069ebd084604,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":580.1945945945945,""y"":1027.5747...",NaN,3

In [6]:
csv.loc[csv['序列编号']=='8f45c5479cec4a17addcba927669cd03']

,用户编号,影像结果编号,序列编号,阴阳性,病灶,影像工具,影像结果类型,影像结果,自定义内容,恶性细胞分类
4439,5211,156486,8f45c5479cec4a17addcba927669cd03,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":309.00221739953713,""y"":1087.401...",NaN,2
4440,5211,156490,8f45c5479cec4a17addcba927669cd03,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":303.6415094339622,""y"":12.132075...",NaN,1
4441,5211,156488,8f45c5479cec4a17addcba927669cd03,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":929.1886792452829,""y"":434.49056...",NaN,1
4442,5211,156494,8f45c5479cec4a17addcba927669cd03,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1212.2830188679243,""y"":948.1698...",NaN,2
4443,5211,156495,8f45c5479cec4a17addcba927669cd03,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1671.1698113207544,""y"":66.92452...",NaN,4
4444,5211,156501,8f45c5479cec4a17addcba927669cd03,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":620.9811320754716,""y"":1037.2075...",NaN,2
4445,5211,156539,8f45c5479cec4a17addcba927669cd03,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1472.5471698113206,""y"":900.2264...",NaN,4

In [7]:
csv.loc[csv['序列编号']=='ae71e02c05f245e5a8a09b14bfaed051']

,用户编号,影像结果编号,序列编号,阴阳性,病灶,影像工具,影像结果类型,影像结果,自定义内容,恶性细胞分类
3531,5211,160634,ae71e02c05f245e5a8a09b14bfaed051,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1235.1132075471696,""y"":151.3962...",NaN,1

In [8]:
csv.loc[csv['序列编号']=='ec0d82b238214f1f90480d91924913b5']

,用户编号,影像结果编号,序列编号,阴阳性,病灶,影像工具,影像结果类型,影像结果,自定义内容,恶性细胞分类
1883,5211,173266,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":36.52830188679245,""y"":224.45283...",NaN,1
1884,5211,173267,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1109.5471698113206,""y"":744.9811...",NaN,1
1885,5211,173265,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":974.8490566037734,""y"":101.16981...",NaN,1
1886,5211,173269,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1349.264150943396,""y"":756.39622...",NaN,1
1887,5211,173272,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1139.2264150943395,""y"":961.8679...",NaN,1
1888,5211,173277,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":867.5471698113206,""y"":409.37735...",NaN,1
1889,5211,173280,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":573.0377358490565,""y"":989.26415...",NaN,1
1890,5211,173286,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1184.8867924528302,""y"":429.9245...",NaN,1
1891,5211,173287,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":162.09433962264148,""y"":566.9056...",NaN,1
1892,5211,173284,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1570.7169811320753,""y"":598.8679...",NaN,1
1893,5211,173294,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1481.6792452830186,""y"":818.0377...",NaN,1
1894,5211,173302,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":79.90566037735849,""y"":71.490566...",NaN,1
1895,5211,173306,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":1723.6792452830186,""y"":25.83018...",NaN,1
1896,5211,173307,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":9.132075471698112,""y"":50.943396...",NaN,1
1897,5211,173304,ec0d82b238214f1f90480d91924913b5,NaN,ANNO9,RECTANGLE,2,"{""point1"":{""x"":100.45283018867923,""y"":498.4150...",NaN,1

In [14]:
best_paiyin=0.989
fnr = 0.1
epoch=100
'epoch_%d_best_paiyin_%.3f_recall_%.3f.pth'%(epoch,best_paiyin, 1-fnr)

'epoch_100_best_paiyin_0.989_recall_0.900.pth'